/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.HienHanh;
import BUS.KhachHangBUS;
import DTO.KhachHang;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kieu Oanh
 */
public class TimKiemKHGUI extends javax.swing.JFrame {

    /**
     * Creates new form TimKiemKHGUI
     */
    public TimKiemKHGUI() {
        initComponents();
        
        LoadAllKH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSKH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txfTimKiemKH = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tblDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ KH", "Tên KH", "SDT", "Giới tính", "Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSKH);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("Tìm kiếm:");

        txfTimKiemKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfTimKiemKHKeyReleased(evt);
            }
        });

        btnThoat.setText("X");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txfTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfTimKiemKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfTimKiemKHKeyReleased
      if (txfTimKiemKH.getText().isEmpty() == false){
          String tuTimKiem = txfTimKiemKH.getText();
          
          TimKiemKH(tuTimKiem);
      }else{
          LoadAllKH();
      }
    }//GEN-LAST:event_txfTimKiemKHKeyReleased

    private void tblDSKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSKHMouseClicked
       HienHanh.setKhachHang(tblDSKH.getValueAt(tblDSKH.getSelectedRow(), 0).toString());
        
        System.out.println("Mã KH: " + HienHanh.getKhachHang()); 
        //BanHangGUI.txMaKH.setText(HienHanh.getKhachHang());
        
    }//GEN-LAST:event_tblDSKHMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void LoadAllKH(){
        ArrayList khachhangArr = new ArrayList();
        DefaultTableModel modelKH = (DefaultTableModel) tblDSKH.getModel();
        modelKH.setRowCount(0);
        
        KhachHangBUS khBUS = new KhachHangBUS();
        
        khachhangArr = khBUS.dockhachhang();
        
        KhachHang khDTO = new KhachHang();
        for (int i = 0 ; i< khachhangArr.size(); i++){
            khDTO = (KhachHang) khachhangArr.get(i);
            
            Object[] row = {khDTO.getMaKH(), khDTO.getHoKH(), khDTO.getTenKH(), khDTO.getSdt(), khDTO.getGioitinh(), khDTO.getMail()};
            modelKH.addRow(row);
            
        }
        
        
    }
    
    private void TimKiemKH(String tuTimKiem){
        ArrayList khachhangArr = new ArrayList();
        DefaultTableModel modelKH = (DefaultTableModel) tblDSKH.getModel();
        modelKH.setRowCount(0);
        
        KhachHangBUS khBUS = new KhachHangBUS();
        
        khachhangArr = khBUS.timkh(tuTimKiem);
        
        KhachHang khDTO = new KhachHang();
        for (int i = 0 ; i< khachhangArr.size(); i++){
            khDTO = (KhachHang) khachhangArr.get(i);
            
            Object[] row = {khDTO.getMaKH(), khDTO.getHoKH(), khDTO.getTenKH(), khDTO.getSdt(), khDTO.getGioitinh(), khDTO.getMail()};
            modelKH.addRow(row);
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemKHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemKHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemKHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemKHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiemKHGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSKH;
    private javax.swing.JTextField txfTimKiemKH;
    // End of variables declaration//GEN-END:variables
}
